services:
  kanban-postgres:
    image: postgres:9.6-alpine
    container_name: kanban-postgres
    environment:
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
      POSTGRES_DB: kanban
    ports:
      - "5432:5432"
    volumes:
      - kanban-data:/var/lib/postgresql/data
  kanban-app:
    build: ./kanban-app
    container_name: kanban-app
    ports:
      - "8080:8080"
    depends_on:
      - kanban-postgres
    environment:
      - DB_SERVER=kanban-postgres
      - POSTGRES_DB=kanban
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban
  kanban-ui:
    build: ./kanban-ui
    container_name: kanban-ui
    ports:
      - "4200:80"
    depends_on:
      - kanban-app
  
volumes:
  kanban-data: